### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#20]
We need a date picker polyfill for browsers without native input type="date" support. Didn't we created one in PI recently? Or is this still in the works. I would love to have it as a stock Pattern and use ut ask for OiRA.

**Comment by jcbrand** [comment]
We have pat-pickadate in PI, but it doesn't actually fall back to the browser for modern browsers AFAIR. We'll have to update it for that.

**Comment by cornae** [comment]
Ok. And didn't we have a discussion on the name? I thought we changed it or even moved to another poly fill.

**Comment by pilz** [comment]
Shouldn't it even be called something like pat-datepicker and be agnostic of the underlying package that implements it?

**Comment by cornae** [comment]
In this case I would say yes. Except with a dash, as datepicker is not yet an English word.

**Comment by jcbrand** [comment]
+1 for pat-date-picker and in core. We can then replace pat-pickadate in PI as well.

**Comment by cornae** [comment]
@pysailor, What is the status of this?

**Comment by cornae** [comment]
I need to know which picker we get and when it's there so that I can style it.

**Comment by pysailor** [comment]
@jcbrand I don't know about this, what needs to be done?

**Comment by jcbrand** [comment]
@pysailor We need to rename pat-pickadate to pat-date-picker and modify it so it only polyfills for older browsers. And we might want to move it to Patterns repo.

**Comment by cornae** [comment]
Can you let me know when I can style something?

**Comment by jcbrand** [comment]
@cornae will do

**Comment by jcbrand** [comment]
Hi @cornae 

I've updated the JS bundle in OiRA's prototype. It now has `pat-date-picker`.

You'll need to explicitly tell it to polyfill. I suspect you might not like this fact, but I think it's for the best because this pattern supports usecases which no browser supports with HTML5, such as timezone support, and only showing time zones.

To use the pattern, you specify which elements you want to see with `show` and you specify whether you want it to polyfill with `behavior`. You'll notice there aren't any true/false values ;)

For example:
`<input type="date" class="pat-date-picker" data-pat-date-picker="show: date; behavior: polyfill"/>`

`<input type="datetime-local" class="pat-date-picker" data-pat-date-picker="show: date, time; behavior: polyfill"/>`

The options are detailed in the readme, see here:  https://github.com/Patternslib/pat-date-picker

**Comment by cornae** [comment]
Do I have some say in property names? For instance: all other patterns use
standard English for property names, not American English.

Op dinsdag 19 mei 2015 heeft JC Brand <notifications@github.com> het
volgende geschreven:

**Comment by jcbrand** [comment]
Yeah, IMHO it's wrong to use UK English property names. Computer related terms have been standardized on US English for ages now.

However, I can change it if necessary.

**Comment by jcbrand** [comment]
CSS is for example US English :)

**Comment by cornae** [comment]
I’m European and proud of it :).

**Comment by cornae** [comment]
Indeed, which is wrong, since especially since it’s a Dutch/Norwegian invention. There have been parsers in the past who accepted ‘colour’ though. Actually, I’m not sure which, but one of our Patterns supports standard English and US English for a certain word. Can’t remember what it was, probably pat-equaliser.

**Comment by jcbrand** [comment]
Yeah, I'm thinking easiest (and most user-friendly) is to just support both variants.

**Comment by jcbrand** [comment]
@cornae: I've changed the pattern's parser to enable us to add aliases.

We can now add an aliases to patterns arguments and I've added the alias `behaviour` to the `behavior` argument.

**Comment by cornae** [comment]
I tried to limit date picker to only use date, not time. The readme advises `pat-date-picker="show: date"`. This however didn't work, I still see time. Date only should also be the default. I could actually not imagine any use case in which I would prefer the time picker over trusted [   ]h [   ]m fields.

Some comments about the properties: 

`date`
This one uses JSON as a value. Patterns don't use JSON to define options. We should translate this to formats that are easy to read and use by everybody.

`separator`
Default value missing

`show`
Fine syntax, but doesn't work.

`behaviour`
Fine, but — like in CSS — there should always be a counter value. Even if it's a fake one.

`time`
JSON it says. Totally unclear to me as a designer what to do here, how to use it or why I would need it. 

`timezone`
Same as time.


I think the pattern is still too immature to be added to stock Patterns. Properties have to be designer proof first. I think I could have helped here, should I have been in involved with the design process of the properties. 

I understand by reading the documentation that in the end, there was still chosen for pickadate as a base. Why was this? Which were the other condidates? I ask because I thought that at first we wanted to leave pickadate adn because the way the markup and the class names are set up is not ideal with this script.

**Comment by jcbrand** [comment]
> I tried to limit date picker to only use date, not time. The readme advises `pat-date-picker="show: date"`.
> This however didn't work, I still see time. Date only should also be the default. I could actually not imagine any use case in which I would prefer the time picker over trusted [   ]h [   ]m fields.

You can `git clone` pat-date-picker and then run `make designerhappy` in there and then go to http://localhost:4001 to see the examples. I just did that and the example with just the date works as expected.

If it doesn't work for you, then you might have an outdated bundle. I just double checked that the PI bundle has the newest dat-date-picker code. Did you run `make fetchrelease` in the prototype?


> `date`
> This one uses JSON as a value. Patterns don't use JSON to define options. We should translate this to formats that are easy to read and use by everybody.

Since the merging of Patterns and Mockup, patterns do support JSON.

> `separator`
> Default value missing

Please provide one.

> `behaviour`
> Fine, but — like in CSS — there should always be a counter value. Even if it's a fake one.

Which is?

> I think the pattern is still too immature to be added to stock Patterns. Properties have to be designer proof first. I think I could have helped here, should I have been in involved with the design process of the properties.

This pattern was copied over from Mockup, which is why it has some JSON values etc. Although this was done with the idea to save time, generally I think copying over patterns from mockup is not ideal.

> I understand by reading the documentation that in the end, there was still chosen for pickadate as a base. Why was this? Which were the other condidates? I ask because I thought that at first we wanted to leave pickadate adn because the way the markup and the class names are set up is not ideal with this script. 

I'm not aware of that. The choice was made by the Mockup team and we copied over their pattern.

**Comment by jcbrand** [comment]
@conae I see Fulvio made a new PI bundle release 13 hours ago. Perhaps before that pat-date-picker was still out of date, so please do `make fetchrelease`.

**Comment by jcbrand** [comment]
@cornae I've created a new ticket in the pat-date-picker repo. I think we should continue the discussion there, since this is more of a Patterns than OiRA thing. Agreed?

**Comment by cornae** [comment]
Agree
