### ISSUE TITLE
Social sharing feature

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#61]

**Comment by pysailor** [comment]
@cornae Believe it or not, this is now becoming relevant again. As a first step, what info do we need from the client? If I remember correctly from back then, it was
* what platforms do you want to share to? Twitter, Facebook, ...?
* what kind of content should be available for the preview?
* where / at what stage (in OIRA) should the sharing option be available?

The interesting aspect is that OIRA tools are only visible when logged in, so the preview + link would need to point to the generic URL of such a tool.
I'd be happy to have a chat on this, but that would have to be next week, since I'm offline the next 4 days.

**Comment by cornae** [comment]
Is monday good for you for a chat on this?

**Comment by pysailor** [comment]
Continued in euphorie/oira.prototype#2
