### ISSUE TITLE
Improve styling "Legal refernces" on action plan

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#65]
Hi,
I had to add "Legal and policy references" also to the action plan (c694010d). And the client explicitly requests that only the heading is shown by default, while the text will only appear after the user clicks "show".
Two questions:
1) Should this really be a `<h3>`? I did not use `<h2>` because that is used for the risk title already. If `<h3>` is correct, does it also need a margin-bottom?
2) The legal references can contains links (see my example code). Can you please provide a similar solutuon as you did in 3af861e?

**Comment by pysailor** [comment]
For 1) I would suggest to give the h3 here a `margin-bottom:1em`, maybe via an extra class if you don't want that generally?

for 2) something like

    article.warning a {
          color: white;
          text-decoration: underline;
        }

might do it. I just don't know how to cause that line to be created using sass, if I look at 3af861e :)

**Comment by cornae** [comment]
It should not be an h2. 

In the typography for article, for this I choose for now separation line between the header of the level h3 and the following content, so that also applies here.

What is the problem with links in legal references? Your reference suggests that the legal references are in a coloured block, but mine aren't in proto…

Do you have any screen grabs or links in proto where things go wrong? Not sure where to start on a solution.

**Comment by cornae** [comment]
The moment I posted my question I realised I was looking at the wrong instance of LR :). I'll have a look what goes on there.

**Comment by cornae** [comment]
The core of the problem lays in the fact that 'show more' or even 'show (which is indeed more correct)' as a one liner underneath a header is a highly unorthodox design solution. I would even suggest not to use the more/less pattern in this case at all, because this is a miss-use. Instead, I'll experiment with collapsibles. This is of course a design change of a design that has already been approved.

**Comment by cornae** [comment]
This is my new design solution.

![image](https://cloud.githubusercontent.com/assets/738601/8919063/cabc8408-34bc-11e5-84df-edb06bdb1bb3.png)

**Comment by pysailor** [comment]
I like it!
I guess the `<h3>` for "legal an policy references", visible when the collapsible is opened, should be removed, since it's just a duplication:
![oira-legal-and-policy](https://cloud.githubusercontent.com/assets/642660/8931824/67b23f38-3539-11e5-9eea-e1490561531e.jpeg)

**Comment by cornae** [comment]
Yes it should. I though I did so in proto one commit later.

**Comment by pysailor** [comment]
:+1:
